import '../styles/about-me.css'
import React from 'react'
import { Icons } from "./Icons"
import { Title } from "./Title"

export const Projects = React.forwardRef((props, ref) => {
    return (
        <section className="projects" ref={ref}>
            <Icons iconName={'svg-2'}/>
            <Title text="Projects" elementType="h2"/>

            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui, eum! Illum vero qui eos assumenda amet ea, itaque placeat cumque alias doloremque magni. Consequuntur earum laborum quos sequi ut tempore aliquid excepturi voluptas deserunt, veniam hic molestiae officiis neque amet, fugit quisquam libero tempora odio rerum? Eius harum quis repellat quas nobis itaque? Quam tempora aut, ex fuga facere iusto earum in omnis consequuntur a molestiae dolores similique beatae nemo et unde, rerum pariatur officia ad consectetur impedit soluta vitae voluptate? Veritatis nobis dolor nisi, mollitia dolorum vel nostrum minus facilis rem, accusantium atque at blanditiis, officiis quos harum! Tempora?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui, eum! Illum vero qui eos assumenda amet ea, itaque placeat cumque alias doloremque magni. Consequuntur earum laborum quos sequi ut tempore aliquid excepturi voluptas deserunt, veniam hic molestiae officiis neque amet, fugit quisquam libero tempora odio rerum? Eius harum quis repellat quas nobis itaque? Quam tempora aut, ex fuga facere iusto earum in omnis consequuntur a molestiae dolores similique beatae nemo et unde, rerum pariatur officia ad consectetur impedit soluta vitae voluptate? Veritatis nobis dolor nisi, mollitia dolorum vel nostrum minus facilis rem, accusantium atque at blanditiis, officiis quos harum! Tempora?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui, eum! Illum vero qui eos assumenda amet ea, itaque placeat cumque alias doloremque magni. Consequuntur earum laborum quos sequi ut tempore aliquid excepturi voluptas deserunt, veniam hic molestiae officiis neque amet, fugit quisquam libero tempora odio rerum? Eius harum quis repellat quas nobis itaque? Quam tempora aut, ex fuga facere iusto earum in omnis consequuntur a molestiae dolores similique beatae nemo et unde, rerum pariatur officia ad consectetur impedit soluta vitae voluptate? Veritatis nobis dolor nisi, mollitia dolorum vel nostrum minus facilis rem, accusantium atque at blanditiis, officiis quos harum! Tempora?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui, eum! Illum vero qui eos assumenda amet ea, itaque placeat cumque alias doloremque magni. Consequuntur earum laborum quos sequi ut tempore aliquid excepturi voluptas deserunt, veniam hic molestiae officiis neque amet, fugit quisquam libero tempora odio rerum? Eius harum quis repellat quas nobis itaque? Quam tempora aut, ex fuga facere iusto earum in omnis consequuntur a molestiae dolores similique beatae nemo et unde, rerum pariatur officia ad consectetur impedit soluta vitae voluptate? Veritatis nobis dolor nisi, mollitia dolorum vel nostrum minus facilis rem, accusantium atque at blanditiis, officiis quos harum! Tempora?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui, eum! Illum vero qui eos assumenda amet ea, itaque placeat cumque alias doloremque magni. Consequuntur earum laborum quos sequi ut tempore aliquid excepturi voluptas deserunt, veniam hic molestiae officiis neque amet, fugit quisquam libero tempora odio rerum? Eius harum quis repellat quas nobis itaque? Quam tempora aut, ex fuga facere iusto earum in omnis consequuntur a molestiae dolores similique beatae nemo et unde, rerum pariatur officia ad consectetur impedit soluta vitae voluptate? Veritatis nobis dolor nisi, mollitia dolorum vel nostrum minus facilis rem, accusantium atque at blanditiis, officiis quos harum! Tempora?</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui, eum! Illum vero qui eos assumenda amet ea, itaque placeat cumque alias doloremque magni. Consequuntur earum laborum quos sequi ut tempore aliquid excepturi voluptas deserunt, veniam hic molestiae officiis neque amet, fugit quisquam libero tempora odio rerum? Eius harum quis repellat quas nobis itaque? Quam tempora aut, ex fuga facere iusto earum in omnis consequuntur a molestiae dolores similique beatae nemo et unde, rerum pariatur officia ad consectetur impedit soluta vitae voluptate? Veritatis nobis dolor nisi, mollitia dolorum vel nostrum minus facilis rem, accusantium atque at blanditiis, officiis quos harum! Tempora?</p>
        </section>
    )
})